name: simple_animated_widgets
description: "simple_animated_widgets is a Flutter package that provides simple, reusable, and customizable animated widgets to enhance your Flutter applications."
version: 0.0.2
homepage: https://github.com/theprantadutta/simple_animated_widgets
repository: https://github.com/theprantadutta/simple_animated_widgets

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: 3.19.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  lint_staged: ^0.5.1
  husky: ^0.1.7

lint_staged:
  "lib/**.dart": dart format --fix && dart fix --apply
